# Generated by Django 4.2.3 on 2023-08-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=45)),
                ('emp_email', models.EmailField(max_length=45)),
                ('emp_phone', models.CharField(max_length=10)),
                ('emp_designation', models.CharField(max_length=20)),
            ],
        ),
    ]
