# Generated by Django 4.2.3 on 2023-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_pic',
            field=models.FileField(default='', upload_to='myapp/event_pic'),
        ),
    ]
