# Generated by Django 4.2.3 on 2023-08-04 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_event_event_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_pic',
            field=models.FileField(default=' ', upload_to='myapp/event_pic'),
        ),
    ]
