# Generated by Django 4.2.3 on 2023-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_event_event_date_event_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_pic',
            field=models.FileField(default=' ', upload_to='myapp/employee_pic'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_designation',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
