# Generated by Django 4.2.3 on 2023-08-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_event_id_employee_emp_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('student_id', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('student_password', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('student_pic', models.FileField(default='', max_length=200, upload_to='myapp/student_pic')),
            ],
        ),
    ]
