# Generated by Django 4.2.3 on 2023-08-11 04:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Feedback_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('feedback_rating', models.CharField(max_length=6)),
                ('feedback_date', models.DateField(default=django.utils.timezone.now)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.student')),
            ],
        ),
    ]
